force-app/main/default/objects/Partner__c/Partner__c.object-meta.xml
<CustomObject>
    <label>Partner</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Partner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partners</relationshipLabel>
    <relationshipName>Partners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Partner__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Partners</relationshipLabel>
    <relationshipName>Partners</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DuplicatePartnerTriggerHandler.cls
public class DuplicatePartnerTriggerHandler {
    public static void preventDuplicates(List<Partner__c> listOfNewPartners){
        
        Set<Id> accountIds = new Set<Id>();
    	Set<Id> opportunityIds = new Set<Id>();
		Map<Id, Partner__c> mapOfPartnerAccounts = new Map<Id, Partner__c>();
    	Map<Id, Partner__c> mapOfPartnerOpportunities = new Map<Id, Partner__c>();
    
    for(Partner__c partner : listOfNewPartners){
        accountIds.add(partner.Account__c);
        opportunityIds.add(partner.Opportunity__c);
    }

    
		for(Partner__c partnerObj: [SELECT Id, Account__c, Opportunity__c
                                     FROM   Partner__c
                                   	WHERE  Account__c IN :accountIds 
                                   	AND    Opportunity__c IN :opportunityIds]){
                               mapOfPartnerAccounts.put(partnerObj.Account__c, partnerObj);
                               mapOfPartnerOpportunities.put(partnerObj.Opportunity__c, partnerObj);                                         
                                     }    
    
    for(Partner__c partnerObj2 : listOfNewPartners){
        if(mapOfPartnerAccounts.containsKey(partnerObj2.Account__c) && mapOfPartnerOpportunities.containsKey(partnerObj2.Opportunity__c))
            partnerObj2.addError('Partner with same account exists');
    	}        
    }
}